language: ruby
before_install:
  - bundle config build.nokogiri --use-system-libraries
bundler_args: --without development
cache: bundler
rvm: 2.1.2
before_script:
  - mysql -e 'create database timecard_test;'
  - cp config/database.yml.sample config/database.yml
  - cp config/omniauth.yml.sample config/omniauth.yml
script:
  - bundle exec rake db:setup
  - bundle exec rspec
